### ISSUE TITLE
help wanted: Link Object in Table

### ISSUE THREAD

**Issue by armanneysi89** [HBM/md-components#181]
It would be helpful to have an example, how to build a column as an Link object (from react-router) an. How can I match a column to a Component?

**Comment by zemirco** [comment]
You can simply pass a component instead of a primitive value (string, number) to the table body. Code taken from the examples.

Passing a string
```
data: [
  ['Ice cream sandwich', 237, 9.0, 37, 4.3, 129, '8%'],
]
```

Passing a component (tested with normal link but react-router Link should work as well)
```
data: [
  [<a href="/ice">Ice cream sandwich</a>, 237, 9.0, 37, 4.3, 129, '8%'],
]
```

Does that help?

**Comment by armanneysi89** [comment]
We tried already to pass an <a>-Tag as a column, but it won't be shown as a link.

**Comment by zemirco** [comment]
Did you remove the quotes when replacing the string with a component? I just tested the above code and it works fine.

**Comment by armanneysi89** [comment]
Ok that was the mistake! Thank you!
