### ISSUE TITLE
Feature Request Select: Enable Property

### ISSUE THREAD

**Issue by armanneysi89** [HBM/md-components#183]
It would be nice to set the property "enable" from outside.

**Comment by lipp** [comment]
@armanneysi89 do you mean the "disable" prop (as for e.g. inputs) ?

**Comment by armanneysi89** [comment]
Just to be able to implement a dependency between selectors (for e.g).
Imagine you have two selectors: 

selector1 and selector2.

Initial state:

selector 1 is enabled 
selector 2 is disabled (grey, it doesn't react if you click on it)

Now you select an item with selector 1.
And the selector can be enabled to select items.
