### ISSUE TITLE
not able to set  submenu in a submenu using the navigation component

### ISSUE THREAD

**Issue by armel22** [HBM/md-components#187]
Below is how  I set the links array
```javascript
let links = [
            { 
                text: 'Projects',
                link: '/runExecutions',
                links: [
                    {
                        text: 'project1', 
                        link:'/project1',
                        links: [{
                            text: 'branch1',
                            link:'/branch1',
                        },
                        {
                            text: 'branch2',
                            link:'/branch2',
                        }]
                    },{
                        text: 'setting', link: '/setting',
                    }]
                },   
     ]
```
did i miss something or this feature is not supported?

**Comment by zemirco** [comment]
This feature is not supported. The Navigation Drawer component has two levels max.

https://material.google.com/patterns/navigation-drawer.html#navigation-drawer-behavior
https://material.google.com/patterns/navigation.html#navigation-combined-patterns
https://material.google.com/layout/structure.html#structure-whiteframes

If you want to go deeper you could use the Tabs component or a List.
