### ISSUE TITLE
to be done until we can show the project to the world

### ISSUE THREAD

**Issue by zemirco** [HBM/md-components#49]
- [x] add playground to all components
- [x] make coveralls work
- [x] add some description and github buttons to examples home page
- [x] fix z-index for codemirror
- [x] add links from online examples to material design spec
- [x] fix #25 
- [x] release new version. should have version 4.0.0 because latest `hbm-react-components` had 3.0.0 and we do not want to override 1.0.0.
- [x] minify script for gh-pages build

**Comment by lipp** [comment]
maybe also add #25 ?

**Comment by zemirco** [comment]
ok. will take care of #25 today.

**Comment by lipp** [comment]
contacted coveralls via email...

**Comment by lipp** [comment]
@zemirco added minify issue

**Comment by lipp** [comment]
@zemirco plans on releasing?

**Comment by zemirco** [comment]
will do so tomorrow

**Comment by zemirco** [comment]
we did it :tada:

**Comment by lipp** [comment]
great! should i post on reddit?

**Comment by zemirco** [comment]
yeah go for it!

**Comment by lipp** [comment]
How the the title be?
I will also post it on echojs

**Comment by lipp** [comment]
"Material Design Components for React" ? @zemirco @Fa-So

**Comment by zemirco** [comment]
sounds good to me

**Comment by lipp** [comment]
upvote:
https://www.reddit.com/r/webdev/comments/53y3yn/material_design_components_for_react/

**Comment by lipp** [comment]
upvote:
https://www.reddit.com/r/javascript/comments/53y41y/material_design_components_for_react/

**Comment by lipp** [comment]
upvote:
http://www.echojs.com/news/20366

**Comment by zemirco** [comment]
https://twitter.com/zemirco/status/778882002569363456

**Comment by lipp** [comment]
we can see the traffic here (only visits on repo though):
https://github.com/HBM/md-components/graphs/traffic

**Comment by zemirco** [comment]
Well done everybody! Congrats on latest relase :) Let's see how it goes.
