### ISSUE TITLE
Rename proposal

### ISSUE THREAD

**Issue by zemirco** [HBM/md-components#72]
Let's rename `hbm-react-components` to `md-components`.

- it's shorter
- it combines Material Design and React Components
- it's easier to find on the web
- it's still free on npm
- we don't really need the company name inside the npm package

What do you think @lipp @Fa-So

**Comment by lipp** [comment]
👍 agree

**Comment by Fa-So** [comment]
Agree

**Comment by lipp** [comment]
@zemirco the repo name remains the same?
